name: azdevops_cli

trigger:
- develop
- main
- features/*
- hotfixes/*
- bugfixes/*
- releases/*
- support/*

pool:
  vmImage: 'Ubuntu-20.04'

variables:
- group: azdevops.cli.vars

steps:
  
  - checkout: self

  - task: gitversion/setup@0
    displayName: 'Install GitVersion $(GitVersion)'
    inputs:
      versionSpec: '$(GitVersion)'

  - task: gitversion/execute@0
    displayName: 'Calculate SemVer'
    inputs:
      useConfigFile: true
      configFilePath: .gitversion.yml
  
  - task: UsePythonVersion@0
    displayName: 'Use python 3.8'
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: 'x64'

  - task: Bash@3
    displayName: 'Update package version'
    inputs:
      targetType: inline
      script: |
        python3 $(Build.SourcesDirectory)/scripts/set-cli-version.py -f $(Build.SourcesDirectory)/src/pyproject.toml
        cat $(Build.SourcesDirectory)/src/pyproject.toml

  - task: Bash@3
    displayName: 'Install application dependencies'
    inputs:
      targetType: 'inline'
      workingDirectory: $(Build.SourcesDirectory)/src
      script: |
        set -x
        python3 -m venv .venv
        source .venv/bin/activate
        python3 -m pip install --upgrade pip
        pip install --target="./.python_packages/lib/site-packages" -r requirements.txt
        pip install -r requirements.txt
      
  - task: Bash@3
    displayName: 'Update pipeline build number'
    inputs:
      targetType: "inline"
      script: |
        echo "##vso[build.updatebuildnumber]$GITVERSION_LEGACYSEMVER"

  # - task: SonarCloudPrepare@1
  #   inputs:
  #     SonarCloud: 'damienaicheh-sonar'
  #     organization: 'damienaicheh'
  #     scannerMode: 'CLI'
  #     configMode: 'manual'
  #     cliProjectKey: 'damienaicheh_azdevops-cli'
  #     cliProjectName: 'azdevops-cli'
  #     cliProjectVersion: '$(Build.BuildId)'
  #     cliSources: '$(Build.SourcesDirectory)/src'
  #     extraProperties: |
  #       sonar.python.coverage.reportPath=$(Build.SourcesDirectory)/src/coverage.xml
  #       sonar.scanner.metadataFilePath=$(Build.SourcesDirectory)/src/report-task.txt

  - task: Bash@3
    displayName: 'Unit tests and coverage'
    inputs:
      targetType: 'inline'
      workingDirectory: $(Build.SourcesDirectory)/src
      script: |
        set -x
        source .venv/bin/activate
        coverage run -m unittest discover
        if [ $? != 0 ] ; then
          exit 1
        fi
        coverage xml
  
  - task: reportgenerator@5
    displayName: 'Generate code coverage report'
    inputs:
      reports: '$(Build.SourcesDirectory)/src/coverage.xml'
      targetdir: '$(Build.SourcesDirectory)/codecoverage'
      sourcedirs: '$(Build.SourcesDirectory)/src'
      verbosity: 'Verbose'
      historydir: '$(codecoveragehistory.directory)'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage report'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/src/coverage.xml'
      reportDirectory: '$(Build.SourcesDirectory)/codecoverage'

  - task: Bash@3
    displayName: 'Build and package the CLI'
    inputs:
      targetType: 'inline'
      workingDirectory: $(Build.SourcesDirectory)/src
      script: |
        source .venv/bin/activate
        pip install build
        python -m build

  # - task: SonarCloudAnalyze@1

  # - task: SonarCloudPublish@1
  #   inputs:
  #     pollingTimeoutSec: '300'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact'
    inputs:
      PathtoPublish: $(Build.SourcesDirectory)/src/dist
      ArtifactName: drop
      publishLocation: Container

  - task: Bash@3
    displayName: 'Tag version'
    inputs:
      targetType: 'inline'
      scripts: |
        #!/usr/bin/env bash
        set -x 
        git config --global user.name $GITTAGUSERNAME
        git config --global user.email $GITTAGUSEREMAIL
        git tag -a $BUILD_BUILDNUMBER $GITVERSION_SHORTSHA -m "$GITTAGMESSAGE"
        git push origin $BUILD_BUILDNUMBER
    # condition: |
    #   and(
    #     succeeded(),  
    #     eq(variables['Build.Reason'], 'IndividualCI'),
    #     or(
    #       eq(variables['Build.SourceBranch'], 'refs/heads/main'),
    #       startsWith(variables['Build.SourceBranch'], 'refs/heads/releases'),
    #       startsWith(variables['Build.SourceBranch'], 'refs/heads/support')
    #     )
    #   )

  - task: Bash@3
    displayName: 'Prepare to package the CLI'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      targetType: 'inline'
      script: |
        pip install twine

  - task: TwineAuthenticate@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      pythonUploadServiceConnection: 'AzDevOpsCliServiceConnection'
      
  - task: Bash@3
    displayName: 'Upload to Pypi'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      targetType: 'inline'
      workingDirectory: $(Build.SourcesDirectory)/src
      script: |
        python3 -m twine upload --skip-existing --verbose --repository azdevops-cli --config-file $(PYPIRC_PATH) dist/*.whl
