name: azdevops_cli

trigger:
- develop
- main
- features/*
- hotfixes/*
- bugfixes/*
- releases/*
- support/*

pool:
  vmImage: 'Ubuntu-20.04'

variables:
- group: azdevops.cli.vars

steps:
  
  - checkout: self
  
  - task: UsePythonVersion@0
    displayName: 'Use python 3.8'
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: 'x64'
  