project:
  name: enigma-infrastructure
pull_request:
  name: 'SCBE-XXXX: Update terraform provider versions'
  branch: 'features/scbe-xxxx'
assets_directory: ../templates/example
repository:
  default_branch: develop
  pattern: 
    regex: ^enigma-infra-per-env-aks$
actions:
  - update:
      target_path: azure_pipeline.yml
      mode: replace-with
      pattern:
        regex: '^\s+-\sgroup:\senigma-infra-version-(?P<replace>[a-z]*)'
      value: primary
 
      
